apiVersion: v1
kind: Pod
metadata:
  name: galliasphere

spec:
  imagePullPolicy: Always
  containers:
  - name:  galliasphere
    image: tdeheurles/galliasphere:latest
    ports:
    - containerPort: 8000
      hostPort:      8200
      name:          galliasphere
